forwardproxy:
#  image: devhub/forwardproxy:latest
  image: gefa-docker.it.gefa.de/devhub/forwardproxy:1.0-a
  ports:
    - "3128:3128" 
  dns:
    - "10.200.64.131"
  volumes:
    - /docker/repository/forward-proxy:/var/spool/squid
  restart: always
  tty: false
  environment:
    parent_proxy: astaro.it.gefa.de 
    parent_port: 8080 
#    proxy_user: GEFA0154 
#    proxy_pass: 8PsPAest
