forwardproxy:
  image: devhub/forwardproxy:latest
  ports:
    - "3128:3128" 
  volumes:
    - /docker/repository/forward-proxy:/var/spool/squid
  restart: always
  tty: false
  environment:
    parent_proxy: astaro.it.gefa.de 
    parent_port: 8080 
    proxy_user: GEFA0154 
    proxy_pass: 
